version: "2"

services:
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    restart: always
    ports:
      - "2181:2181"
   
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    restart: always
    ports:
      - "9092:9092"
  
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

    depends_on:
      - zookeeper


  mysqldb:
    image: mysql:latest  
    container_name: mysqldb.dev
    command: mysqld --user=root --verbose
    restart: always

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "test_password"
