# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_event.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_event.proto\x12\x05order\"i\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x13\n\x0bproduct_ids\x18\x03 \x03(\t\x12\x14\n\x0c\x63reated_date\x18\x04 \x01(\t\x12\x14\n\x0cupdated_date\x18\x05 \x01(\t\"+\n\x0cOrderCreated\x12\x1b\n\x05order\x18\x01 \x01(\x0b\x32\x0c.order.Order\"+\n\x0cOrderUpdated\x12\x1b\n\x05order\x18\x01 \x01(\x0b\x32\x0c.order.Order\" \n\x0cOrderDeleted\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\xad\x01\n\x0cOrderMessage\x12,\n\rorder_created\x18\x01 \x01(\x0b\x32\x13.order.OrderCreatedH\x00\x12,\n\rorder_updated\x18\x02 \x01(\x0b\x32\x13.order.OrderUpdatedH\x00\x12,\n\rorder_deleted\x18\x03 \x01(\x0b\x32\x13.order.OrderDeletedH\x00\x42\x13\n\x11operation_detailsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=28
  _globals['_ORDER']._serialized_end=133
  _globals['_ORDERCREATED']._serialized_start=135
  _globals['_ORDERCREATED']._serialized_end=178
  _globals['_ORDERUPDATED']._serialized_start=180
  _globals['_ORDERUPDATED']._serialized_end=223
  _globals['_ORDERDELETED']._serialized_start=225
  _globals['_ORDERDELETED']._serialized_end=257
  _globals['_ORDERMESSAGE']._serialized_start=260
  _globals['_ORDERMESSAGE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
